# .github/workflows/release.yml
name: release-nightly

on:
  workflow_dispatch:

jobs:
  release-nightly:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup dependencies
        uses: actions/setup-go@v2

      - name: Log tag name
        run: echo "Build for tag ${{ github.ref_name }}"

      - name: Create release
        run: make release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.ref_name }}
          EXTRAFLAGS: "--nightly --config .goreleaser-nightly.yaml"
