name: Trigger nightly build

on:
  workflow_dispatch:

jobs:
  trigger-nightly:
    name: Push tag for nightly build
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: Fetch all tags
        run: git fetch --tags

      - name: Determine the latest commit on main
        id: latest_commit
        run: echo "::set-output name=commit_sha::$(git rev-parse main)"

      - name: Create nightly tag
        run: |
          commit_sha=${{ steps.latest_commit.outputs.commit_sha }}
          tag_name="nightly-$(date +'%Y%m%d')"
          git tag -f $tag_name $commit_sha
          git push origin $tag_name --force
