name: Trigger nightly build

on:
  workflow_dispatch:

jobs:
  trigger-nightly:
    name: Push tag for nightly build
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: Fetch all tags
        run: git fetch --tags

      - name: Determine the latest commit on main
        id: latest_commit
        run: echo "::set-output name=commit_sha::$(git rev-parse main)"

      - uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: "nightly-$(date +'%Y%m%d')"
          force_push_tag: true
          commit_sha: ${{ steps.latest_commit.outputs.commit_sha }}
          message: "Latest nightly build"
          github_token: ${{ secrets.PAT }}
